### ISSUE TITLE
evaluační prostředí

### ISSUE THREAD

**Issue by Tommekster** [jandoubek/pvs-2018#10]
python project + env

**Comment by Tommekster** [comment]
Nahraju modul, který jsem vyvinul ve výzkumáku

**Comment by jandoubek** [comment]
Nevidim to? Asi se to nenahralo

**Comment by jandoubek** [comment]
Komitnul jsem muj zakladni projekt pro evaluacni prostredi.

**Comment by mathew1937** [comment]
Evaluačné prostredie a test fungujú
