### ISSUE TITLE
vyrobit umělá testovací data

### ISSUE THREAD

**Issue by Tommekster** [jandoubek/pvs-2018#5]
* nahrát ve formátu JSON
* popsat v dokumentu (asi wiki)

> Asi bude dobré vzít typického zákazníka a nějakým rozdělením (normálním) "rozmetat" jejich odpovědi.
> Do testovacích dat to chce schovat nějakou strukturu:
> kavárny používají druh kávy, typickému uživateli chutná daná káva, kladně hodnotí relevantní kavárny

**Comment by mathew1937** [comment]
Prvá verzia generátoru testovacích údajov je vytvorená v module "data_generator"
